### ISSUE TITLE
Adding an un-prefixed parameter to a CompositeModel silently collides with the prefixed parameter

### ISSUE THREAD

**Issue by caryan** [lmfit/lmfit-py#710]
#### First Time Issue Code

Yes, I read the instructions and I am sure this is a GitHub Issue.

#### Description

Given a `CompositeModel` with prefixes to avoid name collisions I then want to add a parameter to the `CompositeModel` with a name that corresponds to one of the model components. For example, I may have an individual constant offsets in the component `Model`'s that I want to replace with a global constant offset in the `CompositeModel`.  This silently fails where the correct component parameter values are reported in `ModelResult.best_values` but the added parameter clobbers the reported fit values in `ModelResult.params`

###### A Minimal, Complete, and Verifiable example

A simple example with a sum of two `ConstantModel`'s. Each constant model has a parameter `c` and if I add that parameter back into the `CompositeModel` the reported fit parameters are wrong. 

```python
import numpy as np

from lmfit.models import ConstantModel
from lmfit.model import CompositeModel

# adding different parameter name `offset` works as expected
model = ConstantModel(prefix="comp0_") + ConstantModel(prefix="comp1_")
model.set_param_hint("offset", expr="comp0_c + comp1_c")
params = model.make_params()
fit_result = model.fit(np.ones(10), params=params, x=np.arange(10))
print(fit_result.fit_report())

[[Model]]
    (Model(constant, prefix='comp0_') + Model(constant, prefix='comp1_'))
[[Fit Statistics]]
    # fitting method   = leastsq
    # function evals   = 7
    # data points      = 10
    # variables        = 2
    chi-square         = 1.2326e-31
    reduced chi-square = 1.5407e-32
    Akaike info crit   = -730.736011
    Bayesian info crit = -730.130841
[[Variables]]
    comp0_c:  0.50000000 +/- 2.9451e-09 (0.00%) (init = 0)
    comp1_c:  0.50000000 +/- 2.9451e-09 (0.00%) (init = 0)
    offset:   1.00000000 +/- 3.0007e-20 (0.00%) == 'comp0_c + comp1_c'
[[Correlations]] (unreported correlations are < 0.100)
    C(comp0_c, comp1_c) = -1.000

print(fit_result.best_values)

{'comp1_c': 0.5000000000014566, 'comp0_c': 0.4999999999985433}


# adding back in a parameter `c` clobbers the `compX_c` parameters
model = ConstantModel(prefix="comp0_") + ConstantModel(prefix="comp1_")
model.set_param_hint("c", expr="comp0_c + comp1_c")
params = model.make_params()
fit_result = model.fit(np.ones(10), params=params, x=np.arange(10))
print(fit_result.fit_report())

[[Model]]
    (Model(constant, prefix='comp0_') + Model(constant, prefix='comp1_'))
[[Fit Statistics]]
    # fitting method   = leastsq
    # function evals   = 7
    # data points      = 10
    # variables        = 2
    chi-square         = 1.2326e-31
    reduced chi-square = 1.5407e-32
    Akaike info crit   = -730.736011
    Bayesian info crit = -730.130841
[[Variables]]
    comp0_c:  0.25000000 +/- 1.4726e-09 (0.00%) (init = 0)
    comp1_c:  0.25000000 +/- 1.4726e-09 (0.00%) (init = 0)
    c:        0.50000000 +/- 1.5004e-20 (0.00%) == 'comp0_c + comp1_c'
[[Correlations]] (unreported correlations are < 0.100)
    C(comp0_c, comp1_c) = -1.000

print(fit_result.best_values)

{'comp1_c': 0.49999999999999994, 'comp0_c': 0.49999999999999994}

```

###### Version information
```
Python: 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ]

lmfit: 1.0.1, scipy: 1.6.0, numpy: 1.19.5, asteval: 0.9.21, uncertainties: 3.1.5
```

**Comment by newville** [comment]
@caryan Yeah, that's a bad idea and far too easy to cause confusion.  

Basically, when evaluating a model, the parameters are cycled through and the prefix for each model is stripped - the "ConstantModel()" really needs a parameter named "c". So, in the first example, for each component, the correct prefix is stripped and you get a parameter named "c" that can be sent to "ConstantModel()".  But you also added a parameter named "c".  

I will not label this as "won't fix" at this point, but I'm not sure that we will try to fix this.

**Comment by reneeotten** [comment]
@newville I haven't gone carefully through the code and am certainly not as proficient as you with that part of the code... Could this be a potential issue for the `Model` class as well or only for a `CompositeModel`?

Would it be -easily- possible to emit a warning (or stop) when a user adds a parameter with name that is the same as the basename (i.e., without prefix) of a parameter for one of the elements of a CompositeModel? Perhaps that could happen in the `make_params` function or do you have any other suggestions/concerns?

**Comment by newville** [comment]
@reneeotten @caryan I think this would cause problems with a non-composite Model (have not verified), but it does require a model having a prefix, which would not be too common for a plain model.  
The problem basically arises in `Model.make_funcargs`  and its calls to `Model._strip_prefix`.   
My initial reaction was "yeah, don't do that", and as I started writing this reply I was lukewarm on this idea, but I guess I am seeing this as something that should be fixed.  That is, I guess that such a name clash is not something the user should have to think about, and maybe that un-prefixed "c" would be used by some other Model. 

Basically, at some point, the value of "c" has to be determined when ConstantModel calls the "constant" function.  `Model.make_funcargs` makes a dict of argname/value pairs.  We currently have a single loop through the (ordered) Parameters, in which the current prefix might be stripped.  In the example, here, when calling the "comp0" or "comp1" Constant model function the loop through the parameters will strip out the correct one, putting the appropriate value for "c".  But *then* the parameter "c" is encountered, seen to be a valid function argument,  and so overwrites that entry. 

I think is fixable by doing a two-pass approach: first, fill in the un-stripped parameters and then overwrite those with the de-prefixed ones. I am still a bit worried about unintended consequences of doing this, but we have a lot of tests ;).

As you suggest,  another option would be to raise an exception here if a parameter would overwrite an existing value, which could only happen when stripping the prefix. 

I don't have a strong whether to fix with a two-pass setup of the function argname/value pairs or to raise an Exception, but a reasonable use-case does seem possible.
\

**Comment by reneeotten** [comment]
@newville I would be in favor of not trying to solve things magically as you said there might be unintended consequences - and actually the Model class is the least tested ;)

Anyway, I think we agree that adding a parameter with the same name as is used as argument to the Model function is not a good idea and asking for trouble. I would prefer just to warn the user if she/he is adding such a parameter and say "hey, this parameter name classes with the arguments to the model function, please change its name and try again". That would certainly not brake anything that works now and it is clear for the user what to do. I think @caryan his main point was that it "silently collides" and that would be resolved. If don't have a clear idea yet though where that check would be added best...

**Comment by reneeotten** [comment]
@newville I think this is something we should try and address before a new release (which I think could happen soon, we've collected enough small changes/improvements to do that). 

Do you agree with my last comment above to just warn the user about this and stop? I still don't really know where that check could happen best though, but can look into it.

**Comment by newville** [comment]
@reneeotten I have to admit I haven't thought about this much in the past several months.    But I looked at this (`Model.make_funcargs()`) and I think it is just as easy to fix as to warn about collisions.  I'll try to make a PR soon...

**Comment by newville** [comment]
fixed in master with #732.
